# Change these first
owner: tony-nguyen1 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Nyx
    url: https://nyx.nguyentony.fr/
  - name: CV en ligne
    url: https://cv.nguyentony.fr/
  - name: Aggrégateur de lien
    url: http://link.nguyentony.fr/
  - name: Forgejo auto-hébergé
    url: https://forgejo.nguyentony.fr/
  # - name: IPv6 test
  #   url: forwardemail.net
  #   port: 80
  #   check: "tcp-ping"
  #   ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: Down detector for my websites and services
  introMessage: "**Upptime**, open-source uptime monitor and status page, powered entirely by GitHub Action."
  navbar:
    - title: Status
      href: /upptime
    # - title: GitHub
    #   href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
